export default {
  "is-zero-address": "isZeroAddress",
  "format-safe-to-string": "formatSafeToString",
  "-- tax": {
    type: "separator",
    title: "Tax",
  },
  "format-tax-rate": "formatTaxRate",
  "parse-tax-rate": "parseTaxRate",
  "-- hook": {
    type: "separator",
    title: "Hook",
  },
  "encode-hook-data": "encodeHookData",
  "-- exponential": {
    type: "separator",
    title: "Exponential",
  },
  "compute-exponential-price": "computeExponentialPrice",
  "compute-exponential-tvl": "computeExponentialTvl",
  "encode-exponential-param": "encodeExponentialParam",
  "format-exponential-param": "formatExponentialParam",
  "parse-exponential-param": "parseExponentialParam",
  "generate-exponential-chart": "generateExponentialChart",
  "-- linear": {
    type: "separator",
    title: "Linear",
  },
  "compute-linear-price": "computeLinearPrice",
  "compute-linear-tvl": "computeLinearTvl",
  "encode-linear-param": "encodeLinearParam",
  "format-linear-param": "formatLinearParam",
  "parse-linear-param": "parseLinearParam",
  "generate-linear-chart": "generateLinearChart",
  "-- bonding-curve": {
    type: "separator",
    title: "BondingCurve",
  },
  "compute-bonding-curve-price": "computeBondingCurvePrice",
  "compute-bonding-curve-tvl": "computeBondingCurveTvl",
  "encode-bonding-curve-props": "encodeBondingCurveProps",
  "format-bonding-curve-props": "formatBondingCurveProps",
  "parse-bonding-curve-param": "parseBondingCurveParam",
  "transform-bonding-curve-props": "transformBondingCurveProps",
  "generate-bonding-curve-chart": "generateBondingCurveChart",
};
