name: "Build Test"
on:
  push:
    branches: [main]
  # pull_request:
  #   # The branches below must be a subset of the branches above
  #   branches: [main]

jobs:
  build:
    name: "Check Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          npm install -g pnpm
      - run: |
          pnpm install --no-frozen-lockfile
      - run: |
          pnpm build
